title: CodeRefinery calendars

description: |
  Public CodeRefinery calendars, so that you can easily be reminded
  about and take part in our activities.

  <br><br>

  <b>Warning (2022-03-04):</b> Right now the calendar does not work,
  we need to fix some github-pages stuff.  This will happen within a
  few days
