title: CodeRefinery calendars

description: |
  Public CodeRefinery calendars, so that you can easily be reminded
  about and take part in our activities.

  If you are interested in attending workshops as a learner, subscribe
  to **Workshops**.  If you want to take part in CodeRefinery
  teaching, choose whichever matches you best.
