name: All Training events, both paid and open
description: |
  Training events offered by Coderefinery or its partners. This includes both free and paid events.
include:
  - workshops.yaml
  - workshop-2023-09-19.yaml
  - workshop-2024-03-12.yaml
  - partners.yaml  

events: [ ]
