name: All Training events, both paid and open
description: |
  Training events offered by Coderefinery or its partners. This includes both free and paid events.
include:
  - workshops.yaml
  - partners.yaml

events: [ ]
